### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by jolsen71** [nicolashainaux/symbols-tree-nav#4] opened 2017-04-10 16:41 UTC
[steps to reproduce:]

1. I had 3 files open, one is a large json and it was selected
2. Clicked a tab to switch to a different file to edit and got this exception after Atom thought about it for a bit. I think it maybe due to the order in which events fired in Atom and something symbols-tree-nav expected to have a value hadn't been rendered or created yet.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [symbols-tree-nav](https://github.com/nicolashainaux/symbols-tree-nav) package 0.15.2

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At C:\Users\James\.atom\packages\symbols-tree-nav\node_modules\q\q.js:126

TypeError: Cannot read property '0' of undefined
    at Function.module.exports.TreeNode.TreeNode.content (/packages/symbols-tree-nav/lib/tree-view.coffee:9:8)
    at /packages/symbols-tree-nav/node_modules/space-pen/lib/space-pen.js:156:31)
    at Function.View.buildHtml (/packages/symbols-tree-nav/node_modules/space-pen/lib/space-pen.js:123:10)
    at /packages/symbols-tree-nav/node_modules/space-pen/lib/space-pen.js:155:33)
    at /packages/symbols-tree-nav/lib/tree-view.coffee:5:19)
    at TreeView.module.exports.TreeView.TreeView.setRoot (/packages/symbols-tree-nav/lib/tree-view.coffee:114:23)
    at /packages/symbols-tree-nav/lib/symbols-tree-nav.coffee:129:19
    at _fulfilled (/packages/symbols-tree-nav/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/packages/symbols-tree-nav/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/packages/symbols-tree-nav/node_modules/q/q.js:749:13)
    at /packages/symbols-tree-nav/node_modules/q/q.js:557:44
    at flush (/packages/symbols-tree-nav/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:23.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
aligner 0.22.3 
atom-alignment 0.12.1 
atom-beautify 0.29.17 
atom-keyboard-macros 0.9.2 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-typescript 11.0.1 
block-travel 1.0.5 
busy-signal 1.3.0 
coffee-compile 0.25.0 
color-picker 2.2.5 
custom-title-jolsen 1.0.1 
figlet 0.5.4 
file-types 0.5.5 
file-watcher 1.1.0 
git-history 3.3.0 
git-log 0.4.1 
git-plus 7.3.3 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
imdone-atom 2.2.2 
indent-guide-improved 1.4.12 
intentions 1.1.2 
keyboard-scroll 0.7.0 
language-apache 1.7.0 
linter 2.1.2 
linter-flake8 2.1.5 
linter-package-json-validator 1.0.1 
linter-pycodestyle 2.0.2 
linter-rubocop 1.1.1 
linter-ui-default 1.2.2 
markdown-scroll-sync 2.1.2 
merge-conflicts 1.4.4 
method-separator 0.2.0 
minimap 4.27.1 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-selection 4.4.0 
minimap-split-diff 0.3.7 
open-recent 5.0.0 
outline-selection 0.3.1 
path-copy 0.14.0 
perltidy 4.0.0 
project-manager 3.3.4 
project-view 0.6.2 
python-debugger 0.2.0 
python-tools 0.6.9 
quick-scroll 2.1.3 
remember-file-positions 0.2.2 
sort-lines 0.14.0 
split-diff 1.3.0 
Sublime-Style-Column-Selection 1.7.4 
symbols-list 2.4.0 
symbols-tree-nav 0.15.2 
symbols-tree-view 0.14.0 
sync-settings 0.8.1 
todo-show 1.11.0 
trailing-spaces 0.4.0 
url-encode 0.5.0 
xml-formatter 0.10.0 
```

**Comment by nicolashainaux** [comment] 2017-04-11 13:57
OK, it would be interesting to know if the same situation triggers the same bug again.
Nevertheless, this seems to be about a bit of code I wrote (to support colors from syntax theme).
If you do not use colors from syntax theme at all, then you shouldn't get this bug.
However, I add a patch to prevent the bug and will publish it at once.

**Comment by nicolashainaux** [comment] 2017-04-11 14:14
This should be correct now. Tell me if this bug shows up again.

**Comment by nicolashainaux** [comment] 2017-04-14 16:10
I close this issue, I'll reopen it if the bug shows up again (but it shouldn't).
Thanks for having reported it!

**Comment by sjdawson** [comment] 2017-06-20 08:42
Hi, just had this error pop up when switching between projects.

1. Had a project open that was showing the tree-view.
2. Opened Project Manager's list view
3. Switched to a new project (**no files in buffer**)

The error _only_ appears when there's no files in the buffer of the project being switched to.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [symbols-tree-nav](https://github.com/nicolashainaux/symbols-tree-nav) package 0.15.3


### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /home/steve.dawson/.atom/packages/symbols-tree-nav/node_modules/q/q.js:126

TypeError: Cannot read property '0' of undefined
    at Function.module.exports.TreeNode.TreeNode.content (/packages/symbols-tree-nav/lib/tree-view.coffee:9:8)
    at /packages/character-table/node_modules/space-pen/lib/space-pen.js:156:31)
    at Function.View.buildHtml (/packages/character-table/node_modules/space-pen/lib/space-pen.js:123:10)
    at /packages/character-table/node_modules/space-pen/lib/space-pen.js:155:33)
    at /packages/symbols-tree-nav/lib/tree-view.coffee:5:19)
    at TreeView.module.exports.TreeView.TreeView.setRoot (/packages/symbols-tree-nav/lib/tree-view.coffee:105:23)
    at /packages/symbols-tree-nav/lib/symbols-tree-nav.coffee:129:19
    at _fulfilled (/packages/symbols-tree-nav/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/packages/symbols-tree-nav/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/packages/symbols-tree-nav/node_modules/q/q.js:749:13)
    at /packages/symbols-tree-nav/node_modules/q/q.js:557:44
    at flush (/packages/symbols-tree-nav/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -4:12.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -4:04.6.0 symbols-tree-nav:toggle (input.hidden-input)
     -1:29.5.0 project-manager:list-projects (input.hidden-input)
     -1:26.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
character-table 0.4.3 
docblockr 0.10.3 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.7 
flex-tool-bar 0.12.0 
hard-wrap 1.1.0 
highlight-selected 0.13.1 
minimap 4.28.2 
minimap-cursorline 0.2.0 
minimap-highlight-selected 4.6.1 
php-twig 4.0.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
pretty-json 1.6.3 
process-palette 0.12.1 
project-manager 3.3.5 
project-viewer 1.1.2 
sort-lines 0.14.0 
symbols-tree-nav 0.15.3 
todo-show 1.11.0 
tool-bar 1.1.0 
typewriter 0.7.0 
```

**Comment by nicolashainaux** [comment] 2017-06-21 04:33
It looks very similar to the first post stack trace. Actually, I cannot find again how this stack trace led me to the bug correction I made... Now investigating this stack trace again, the error does not make much sense to me, unfortunately. Apparently it does not refer to code I wrote (I really wonder how this led me to bugfix #4 the last time).

It looks like the root variable returned by the parser() function is undefined. Maybe something happens too quickly or in a special case, parser() did return something undefined, or nothing at all.

Moreover, I cannot reproduce the bug. Did I understand well? You have for instance one project open (with symbols-tree-nav on). You open a new project (alt-shit-P > pick one project) that opens in a new atom window and were you left no file open the last time you closed it. Is this correct? Does it trigger the bug every time you do this? On several different projects?

It would be really good if other devs could investigate it too, and hopefully find the origin of the bug...

**Comment by nicolashainaux** [comment] 2017-06-21 04:50
No idea whether this makes a difference, or not, but my electron package is more up to date than yours (1.4.16-2; I'm using Manjaro XFCE).

**Comment by sjdawson** [comment] 2017-06-21 07:43
> You have for instance one project open (with symbols-tree-nav on). You open a new project (alt-shit-P > pick one project) **that opens in a new atom window** and were you left no file open the last time you closed it. Is this correct? Does it trigger the bug every time you do this? On several different projects?

It doesn't happen when opening the project in a new window. Sorry, I hadn't thought to mention that I have project-manager setup to open in the same window by default - didn't think that would have been related. When opening in the same window the bug appears every time.

Had a quick try in the beta atom release (as a quick way to check a different version of Electron):

**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.2
**Thrown From**: [symbols-tree-nav](https://github.com/nicolashainaux/symbols-tree-nav) package 0.15.3

And it still gets thrown in there.

**Comment by nicolashainaux** [comment] 2017-06-21 09:48
Fine, it's not always possible to think of all details at once.
Now I can reproduce the bug, what opens new possibilities to hunt for it! Hope I can find the fix now.

**Comment by nicolashainaux** [comment] 2017-06-21 10:17
OK, so I have found a fix that prevents the bug to show up.
But I am not sure that it does not break anything else. I can only say it should not...
I simply test if the variable root is defined before proceeding to build the view. If there's no root, then nothing happens. (So if there's no file, there's no root, nothing happens).
I will work with it for a while a see if it triggers another problem or not, before releasing a new version.
Would you like to try the fix too?

**Comment by sjdawson** [comment] 2017-06-21 10:19
Yeah, glad to test. :+1:

**Comment by nicolashainaux** [comment] 2017-06-21 10:36
OK, so the easiest way is to modify directly the package's code (I suppose you have installed it the normal way, through Settings > Install...).
The file to edit is `.atom/packages/symbols-tree-nav/lib/symbols-tree-nav.coffee`.
From line 129: replace:
```
        @treeView.setRoot(root)
        @updateContextMenu(types)
        @focusCurrentCursorTag()
```
by:
```
        if root?
          @treeView.setRoot(root)
          @updateContextMenu(types)
          @focusCurrentCursorTag()
```
(the three lines get executed only if root is defined, they are only shifted of 2 spaces to the right).
Then save, close and restart atom.
The bug shouldn't show up anymore.
If anything goes wrong, just edit the file to get back to the previous version, without the `if`.

**Comment by sjdawson** [comment] 2017-06-21 11:59
Still getting the same error with that in place, though further investigation has shown that it will happen when the project being _switched from_ has an open instance of symbols-tree-nav. If it's closed before the switch - there's no error.

**Comment by nicolashainaux** [comment] 2017-06-21 12:52
Hum, I don't have it any longer, but I see new errors that I didn't have before. I need to investigate further and better understand the way it is started... Hope I'll find something...

**Comment by sjdawson** [comment] 2017-06-21 13:14
I'll revert the change locally - give me a shout when you have anything new for me to tryout!

Will keep an eye open for anything that might be relevant to this issue, too.

**Comment by nicolashainaux** [comment] 2017-06-21 14:01
This time, I think I got it.

But I still observe something strange I didn't notice before, maybe because I did not pay attention. Actually, as I used to open a new project in a new window, maybe I couldn't have noticed that.

So, can you tell me if, with the untouched 15.3 version of symbols-tree-nav, when you switch to another non empty project (there is at least one file open) (so, not the case you spotted), from a project where symbols-tree-nav is open and visible, you do have to toggle symbols-tree-nav twice to see its panel or if its panel is visible at once, without requiring to toggle symbols-tree-nav at all?

**Comment by sjdawson** [comment] 2017-06-21 14:20
> you do have to toggle symbols-tree-nav twice to see its panel or if its panel is visible at once, without requiring to toggle symbols-tree-nav at all?

Yes, I can reproduce it as described. The panel minimises - and it needs to be toggled off and back on again to appear normally (There's a small, 1px shift in the right hand side when you toggle it off) but after this, it's displaying the right symbols from the file.

**Comment by nicolashainaux** [comment] 2017-06-21 15:09
Thanks!

So, alright, this is just another issue. It looks unrelated to the one with the switching to an empty project. But much more difficult to solve, unfortunately: it triggers an exception (that remains hidden) from an internal component of atom.
And indeed it does not happen when opening the new project in a new window, since at start, symbol-tree-nav is off and requires to be toggled (once) and there's no exception raised in that case.

If you want to try the patch, here it is:
- the previous modification is useless
- this time it happens in `.atom/packages/symbols-tree-nav/lib/tree-view.coffee`.
From line 10, replace: 
```
      [first, ..., language] = atom.workspace.getActiveTextEditor()?.getGrammar()?.scopeName.split "."

```
by: 
```

      scopeName = atom.workspace.getActiveTextEditor()?.getGrammar()?.scopeName
      if scopeName?
        [first, ..., language] = scopeName.split "."
      else
        language = undefined
```

If you do confirm this patch does remove the bug, then I'll publish a new version including it.

**Comment by sjdawson** [comment] 2017-06-22 07:22
> If you do confirm this patch does remove the bug, then I'll publish a new version including it.

Tested that just now, and can confirm I'm no longer getting the error message from the initial report. :+1: 

Nice work! :smiley:

**Comment by nicolashainaux** [comment] 2017-06-22 13:14
Good! I think that's all right now. I publish it as a new patch. If anything would still go wrong, it's not too late to re-open it.
Thanks for your feedback!

**Closed by nicolashainaux** 2017-06-22 13:14 UTC
Labels: bug
